"""empty message

Revision ID: b3ae63df0ed5
Revises: 
Create Date: 2019-04-03 01:44:12.475665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ae63df0ed5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_address'), 'office', ['address'], unique=False)
    op.create_index(op.f('ix_office_city'), 'office', ['city'], unique=False)
    op.create_index(op.f('ix_office_state'), 'office', ['state'], unique=False)
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('specialty', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_first_name'), 'doctor', ['first_name'], unique=False)
    op.create_index(op.f('ix_doctor_last_name'), 'doctor', ['last_name'], unique=False)
    op.create_index(op.f('ix_doctor_rating'), 'doctor', ['rating'], unique=False)
    op.create_index(op.f('ix_doctor_specialty'), 'doctor', ['specialty'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_specialty'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_rating'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_last_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_first_name'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_office_state'), table_name='office')
    op.drop_index(op.f('ix_office_city'), table_name='office')
    op.drop_index(op.f('ix_office_address'), table_name='office')
    op.drop_table('office')
    # ### end Alembic commands ###
